### ISSUE TITLE
How can i delete project or images?

### ISSUE THREAD

**Issue by readthecodes** [vmware/harbor#112]
I can't delete my own project and images, even my role is Project Admin.

**Comment by int32bit** [comment]
Not implemented, yet ?

**Comment by ywk253100** [comment]
The deletion of repositories and tags is in development and will be available soon.
This function uses registry's deletion API and GC. API is responsible for the soft deletion and GC will delete the real data. 
GC will be supported in registry 2.4 and it can only be started by yourself using gc command. See https://github.com/docker/distribution/blob/master/docs/garbage-collection.md

The deletion of projects is not supported for now.

**Comment by xiaods** [comment]
currently we can forget it until GC enabled

**Comment by elianka** [comment]
GC enabled, meanwhile harbor didnot support delete yet.

**Comment by reasonerjt** [comment]
@elianka  for image deletion please see #270 for details.

**Comment by dmajere** [comment]
Hi guys,
@reasonerjt noticed that due to auditing purpose you can not delete a project as the audit logs are associated to the project by id.

I think that this limitation can be mitigated by introducing an additional field Deleted or Dropped to the project structure. It can be set to true, when project is deleted. This way we won't loose project Id.
Probably name of the deleted project should be set to 'None' or something like this, so the real name could be reused by another project.

**Comment by fuhbar** [comment]
Would be nice if deleting of projects is possible.

**Comment by manishjhawar** [comment]
:+1:

**Comment by dmajere** [comment]
Hi guys, so, is there any roadmap for this? Maybe I can help with something?

**Comment by biolounge** [comment]
Its a needed functionality. Please implement it.

**Comment by ywk253100** [comment]
Thank you all guys for the feedback. The deletion of repositories is supported already. And the deleting projects is also available in the next release soon. I will close this issue first, if you have any question, feel free to reopen it.
