### ISSUE TITLE
OVA deployment, re-configured option take no effect to the harbor.cfg

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1155]
I setup OVA deployment, shut down power, turn 'verify remote cert'  to 'off', powered on, but it takes no effect to the `harbor.cfg` against to the changed setting.

Error log on `subsequentboot.log`:
`Another app is currently holding the xtables lock. Perhaps you want to use the -w option?`

**Comment by reasonerjt** [comment]
This is because the iptables command failed, and the the harbor.cfg configuration is canceled.
We probably need to do the following:
1)add -w to iptables so it'll wait for the xtables lock to release.
2)add set +e before some statements such that in case some of them fail the configuration process may continue.

**Comment by ywk253100** [comment]
Fixed by #1164 .
