### ISSUE TITLE
Replication do not sync after changed

### ISSUE THREAD

**Issue by gunboe** [vmware/harbor#1243]
Hi all,
I've two Harbor 0.4.5, A and B. "A" is replicating a Project on "B".
After replication is completed, all images in Project are copied. But, if I remove one image replicated on "B", this image is no more replicated again. I hopped that Harbor "A" would be copied this image once again and keep replicated all images, but didn't. I've waited for 3 days, and nothing happen.
However, If I restart (disable/enable) the Replication job, the Image from Harbor "A" is copied to "B".
Is that a normal feature or a Issue? thanks.

**Comment by ywk253100** [comment]
It is working as design.

**Comment by gunboe** [comment]
Should not the Source maintain a "Replica" similar to it? Even though a user have removed accidentally a Image in Destination?
So in that case, the Source would send a new Image to Destination.

**Comment by reasonerjt** [comment]
We call it replication policy because it's uni-directional.
So source will not know what happen to destination.

**Comment by gunboe** [comment]
Would it be better if the Replication reapply the Policy from time to time, like a crond entry? Rather than disable and enable the Replication Policy and a new Image be copied to the Destination again?

**Comment by hainingzhang** [comment]
The destination is not supposed to delete the image in a one-way replication scenario. It is not realistic for the source to check periodically whether the destination has deleted some images. This not only wastes bandwidth, but also it is hard to predict the behavior of the replication. Stop and restart the policy helps resolve this issue. 

Since this is working as design, closing it for now. Please reopen if there is a need.
