### ISSUE TITLE
Retrieve list of projetcs and repositories (even some of the removed ones) WITHOUT any auth

### ISSUE THREAD

**Issue by It4lik** [vmware/harbor#1308]
Hi, 

I'm experiencing a really annoying problem which is data leak from the registry. 

I have a Portus registry that's also running and it seems like i'm **not** able to retrieve these informations. Then, this **must** come from your implementation of the registry (or mine ?)

I'm using a LDAP backend to authenticate my user, and that's actually workin from the WebUI/docker login (authenticate known users, and refuse wrong credentials). But if I use hand-crafted GET request (using curl, as my script below), I'm able to bypass (more or less) the authentication. 

I only tried with URI _/v2/_catalog_ . 

I'm pinning the script that i'm using to exploit the data leak : http://pastebin.com/2VzkNPeM
- get it
- make it executable
- run it with -h your.registry.org
- it will output a curl command that you can run (and customize if you want)
- run the curl command, that should retrieve all projects/repos

What the script does : 
- make a first request to get information about registry 
- make a second request specifying these informations (realm, service, scope) + user's credentials (in Harbor's case, this can be anything...). This is used to retrieve the token. 
- make a third and last request, using the token (that we're supposed to get ONLY IF we successfully authenticated before) to list projects/repos

It4.

**Comment by reasonerjt** [comment]
Thanks for raising the issue, this was intentional, when we implement the search feature we allow user to search the repo without logging in, hence, the token service returns a token valid for list catalog even no username and password are provided.

I agree this is an issue in security, there are some others in Harbor, we have plan to walk through the flows and refine the security issues, let me keep this open

**Comment by reasonerjt** [comment]
Fixed, verified with the shell script.
