### ISSUE TITLE
Menu in datagrid gets cropped

### ISSUE THREAD

**Issue by lweitzman** [vmware/harbor#1614]
the menu in datagrids gets cropped when near the bottom of the datagrid
![screen shot 2017-03-15 at 4 26 28 pm](https://cloud.githubusercontent.com/assets/626032/23969310/66940562-099c-11e7-92a3-559650ab956f.png)

**Comment by steven-zou** [comment]
A known issue, have started to fix

Same issue with #1621

**Comment by steven-zou** [comment]
@lweitzman 

  This drop down menu is implemented by ourselves, not the standard clarity embedded component because they did not release it. Checking today, they have release this component in version 0.8.7, but it can be only placed as the first column, not the last column. Do we switch to the new Clarity menu component?

See https://vmware.github.io/clarity/documentation/datagrid.

**Comment by lweitzman** [comment]
as long as we are consistent, placing it at the front is ok

**Comment by steven-zou** [comment]
Adopted Clarity action flow component for all related components.
Drop down actions are placed in the position before first column.
In the initial state, the indicator will be hidden and will appeared when user click rows

**Comment by lweitzman** [comment]
can you show the indicator on hover instead of click. then click opens the menu

**Comment by steven-zou** [comment]
A bug of Clarity. Will use Clarity@0.8.7 to avoid the issue.

**Comment by steven-zou** [comment]
@lweitzman 

  Can you verify this issue?
