### ISSUE TITLE
[UI] Cannot understand the error message(Forbidden) in the new replication rule dialogue.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#1694]
![forbidden](https://cloud.githubusercontent.com/assets/2841473/24128699/89bc3dd6-0e18-11e7-9ade-c91d99f03e9a.png)

**Comment by wy65701436** [comment]
what does "Forbidden" mean?

**Comment by reasonerjt** [comment]
Looks like a http 403, could you check the developer tool from browser?

**Comment by wy65701436** [comment]
![403](https://cloud.githubusercontent.com/assets/2841473/24130109/aa092d52-0e21-11e7-8c3b-495fe4179fe9.png)

**Comment by wy65701436** [comment]
@steven-zou  attached is the 403 response.

**Comment by wy65701436** [comment]
maybe, we can have an error message wrapper. The output should be the readable message for the end user.

**Comment by steven-zou** [comment]
We have message wrapper, but unfortunately sometimes there are no meaningful messages returned by backend service.

We have setup a rule for handling error messages:

If there is an error returned,
  check the existing of error.message, if yes display it, otherwise
  check the existing of error._body, if yes display it, otherwise,
  show the general error message like 'Some errors have occurred when performing backend service calling: ' + error.

**Comment by steven-zou** [comment]
@wknet123 

  Please take a loot at this issue. We can have a discussion based on my above proposal.

**Comment by reasonerjt** [comment]
Maybe to avoid user seeing unreadable information on UI. 
We only apply this approach:
***Some errors have occurred when performing backend service calling: ' + error.***

**Comment by steven-zou** [comment]
General error message handling problem. Will refactor the error handling mechanism.

**Comment by steven-zou** [comment]
@wy65701436 @reasonerjt @lweitzman @tonycgil @akshayl @wknet123 

Propose of error handling:

1. Map the error to the following unified messages based on the status code
400: (If this error is returned in UI, must be a bug) We're unable to perform your operation_(action?)_ because of bad request. 
401: Your session is invalid or has expired. You need to sign in to continue your operation
403: You are not allowed to perform the operation because of lacking required privileges. <Please confirm you have the right role or membership> 
404: We're sorry what you're requesting is not existing in our system. <Please confirm everything is valid>
409: We're unable to perform your operation because what you're submitting is already existing. <You can adjust your data to avoid conflict>
500: We're unable to perform your operation because server internal errors have occurred. <Please try again later>
ELSE: Unknown errors have occurred. Please try again later

For some specific scenario, such as email/ldap verification, we can provide concrete error message.

Failed to verify mail configuration with error: <error returned by backend service if message is meaningful>

What's your opinions?

**Comment by wy65701436** [comment]
are they stored in the configuration file? If so, it has the expand-ability and easy to do the globalization.

403: Insufficient access rights to perform the operation.
404: We're sorry the requested url was not found on this server.

**Comment by steven-zou** [comment]
Right, they're stored in message files which support globalization.

"404: We're sorry the requested url was not found on this server." : Not only page, sometimes including data entries/items not found.

**Comment by lweitzman** [comment]
Modify the message as shown below. use the term "action" instead of "operation"
when adding text to the json file, let me know so i can review it.
don't think we need the text in the "[ ]" because its obvious in most cases:
thanks,

400: (If this error is returned in UI, must be a bug) We're unable to perform your operation(action?) because of bad request.
redo: We are unable to perform your action because of a bad request.

401: Your session is invalid or has expired. You need to sign in to continue your operation
redo:  Your session is invalid or has expired. You need to sign in to continue your action.

403: You are not allowed to perform the operation because of lacking required privileges. [Please confirm you have the right role or membership]
redo: You do not have the proper privileges to perform the action.

404: We're sorry what you're requesting is not existing in our system. [Please confirm everything is valid]
redo: Your request can not be completed because the object does not exist. 

409: (At present we have done pre-check to avoid this situation in mail,username and project) We're unable to perform your operation because what you're submitting have conflicting items with existing ones. [You can adjust your data to avoid conflict]
redo: We are unable to perform your action because your submission has conflicts.

500: We're unable to perform your operation because server internal errors have occurred. [Please try again later]
redo: We are unable to perform your action because internal server errors have occurred. 

ELSE: Unknown errors have occurred. Please try again later.

**Comment by steven-zou** [comment]
I'll implement a new error handler service based on the above agreement!
Change owner to me!

**Comment by wy65701436** [comment]
close it as fixed.
