### ISSUE TITLE
Small "Login screen" fixes

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#2011]
Here are some login fixes to finalize the login

![login-details](https://cloud.githubusercontent.com/assets/25991813/25007955/0fae9a0a-2017-11e7-942c-c12b2f750390.png)

**Comment by steven-zou** [comment]
Fixed in master branch.

<img width="735" alt="2017-04-25 2 31 25" src="https://cloud.githubusercontent.com/assets/5753287/25373321/c44518be-29cb-11e7-80fb-cd0ee95f895f.png">
<img width="1204" alt="2017-04-25 2 34 33" src="https://cloud.githubusercontent.com/assets/5753287/25373334/d4affe44-29cb-11e7-871c-184e7ab39190.png">

**Comment by tonycgil** [comment]
Thanks!
