### ISSUE TITLE
Left nav and page title alignment

### ISSUE THREAD

**Issue by tonycgil** [vmware/harbor#2012]
Center left nav and "Projects" nav with page title:
![left-nav-alignments](https://cloud.githubusercontent.com/assets/25991813/25008410/7587b978-2018-11e7-8983-aa5eb8d4ea2c.png)

**Comment by steven-zou** [comment]
Fixed in master.

<img width="260" alt="2017-04-25 4 21 11" src="https://cloud.githubusercontent.com/assets/5753287/25375681/17adbcd8-29d4-11e7-880f-527a07ac41b3.png">
<img width="477" alt="2017-04-25 4 25 44" src="https://cloud.githubusercontent.com/assets/5753287/25375692/1d0b89bc-29d4-11e7-9b32-eb097bceec7f.png">

**Comment by tonycgil** [comment]
Thanks!
