### ISSUE TITLE
How to set Harbor use external redis store user loging session?

### ISSUE THREAD

**Issue by jackpgao** [vmware/harbor#2171]
I use Harbor as a basic Docker Image Service.

So I use multi Harbor instance to build a solid service with HA.

I use mfs as backend storage, the Harbor instance share the same data.

And i use a external MySQL store basic info:

sed -i 's/db_password = root123/db_password = registry_pass/'  harbor.cfg
for file in `find . -name "env" -exec grep MYSQL --color -H {} \; | awk -F':' '{print $1}' | sort | uniq `

do
sed -i 's/MYSQL_HOST=mysql/MYSQL_HOST= mysql_domain/' $file
sed -i 's/MYSQL_PORT=3306/MYSQL_PORT=3304/' $file
sed -i 's/MYSQL_USR=root/MYSQL_USR=registry/' $file 
sed -i 's/MYSQL_ROOT_PASSWORD=root123/MYSQL_PWD=registry_pass/' $file 
sed -i 's/MYSQL_PWD=root123/MYSQL_PWD=registry_pass/' $file 
done 

find . -name "env" -exec grep MYSQL --color -H {} \;   

http://7xs54v.com1.z0.glb.clouddn.com/Harbor架构图.png

But I didn't get it 'How to set Harbor use a external Redis store user loging session'？Please help.

**Comment by reasonerjt** [comment]
We have some code but it's for internal experiment.

So you may need to manual update conf of beego, to use redis storing your session data.

**Comment by jackpgao** [comment]
Should I add this:
_REDIS_URL=redis_host:port

to:
common/templates/ui/env ?

**Comment by reasonerjt** [comment]
You can try, but this is not well tested.

**Comment by jackpgao** [comment]
I tried, but it seems failed....

Will the following release version have this function?

**Comment by reasonerjt** [comment]
Not in high priority

**Comment by jackpgao** [comment]
It works!

The arch is like this:
http://7xs54v.com1.z0.glb.clouddn.com/14937981287261.jpg


Besides the shared session in redis, you also have to make the token service be the same, that is to say, make sure the multi Harbor instance share the same key and certificate. 

Look at this one:
https://github.com/vmware/harbor/blob/master/docs/customize_token_service.md

**Comment by jprateekvmware** [comment]
Thanks so much
 working fine for me as this is must have for having HA

**Comment by todaygood** [comment]
Hi , I met an issue on latest harbor version v1.3.0-rc1.

I found  I failed to login in on web after  configured _REDIS_URL  and use same root.crt ,  If I remove 
_REDIS_URL, the issue was disappeared.

I don't found any clue from log file.

[root@harbor-1 harbor]# grep REDIS  common/config/ui/env 
_REDIS_URL=192.168.63.246:6379

[root@harbor-2 harbor]# grep REDIS  common/config/ui/env 
_REDIS_URL=192.168.63.246:6379

[root@harbor-1 harbor]#  md5sum  common/config/registry/root.crt 
3571d3508aafec0a5a159c158e478d4b  common/config/registry/root.crt

[root@harbor-2 harbor]# md5sum  common/config/registry/root.crt 
3571d3508aafec0a5a159c158e478d4b  common/config/registry/root.crt

[root@harbor-1 harbor]# md5sum  common/config/ui/private_key.pem 
dbcd32dfd738bd5826ca93855698135a  common/config/ui/private_key.pem
[root@harbor-2 harbor]#  md5sum  common/config/ui/private_key.pem 
dbcd32dfd738bd5826ca93855698135a  common/config/ui/private_key.pem

**Comment by jakirpatel** [comment]
I surely think my problem https://github.com/goharbor/harbor/issues/6075 is related to this.
