### ISSUE TITLE
Links on github project website result in 404 error

### ISSUE THREAD

**Issue by bwuch** [vmware/harbor#2537]
On the page https://vmware.github.io/harbor/ there are links for "Installation Guide of HVA" and "User Guide of HVA" both of which currently result in 404 errors.

**Comment by stuclem** [comment]
The docs for the OVA deployment of just Harbor (rather than OVA deployment with VIC 1.1) are now in a separate branch, and relate only to version 0.5:
- https://github.com/vmware/harbor/blob/release-0.5.0/docs/installation_guide_ova.md
- https://github.com/vmware/harbor/blob/release-0.5.0/docs/user_guide_ova.md

I think that these HVA links should be removed from https://vmware.github.io/harbor/.

**Comment by reasonerjt** [comment]
I agree, thanks. @stuclem

**Comment by reasonerjt** [comment]
@drukelly  I've just found you have been making update to the branch "gh-pages", could you help us make the update to remove the HVA links?

**Comment by stuclem** [comment]
@reasonerjt, I can do it.

**Comment by stuclem** [comment]
Removed. Here's the updated page in my branch: https://stuclem.github.io/harbor/#gettingStarted

**Comment by stuclem** [comment]
Removed and published: https://vmware.github.io/harbor/#gettingStarted
