### ISSUE TITLE
两个harbor之间无法复制的问题

### ISSUE THREAD

**Issue by 4680185** [vmware/harbor#2845]
docker  Server Version: 1.12.6
 docker-compose version 1.14.0, build c7bdf9e

我有2个harbor服务器，在他们之间做镜像同步时，在复制管理页面，创建目标后，点击测试连接时，测试连接失败，日志和配置信息如下

[harborlog.tar.gz](https://github.com/vmware/harbor/files/1168589/harborlog.tar.gz)

[harbor.cfg.tar.gz](https://github.com/vmware/harbor/files/1168595/harbor.cfg.tar.gz)

**Comment by ywk253100** [comment]
According to the log "failed to ping registry http://192.168.18.102: Get http://192.168.18.102/v2/: Get http://registrybackup.ctyun.cn/service/token?service=harbor-registry: dial tcp: lookup registrybackup.ctyun.cn: no such host", the root cause is the hostname "registrybackup.ctyun.cn" can not be resolved inside the container.

**Comment by 4680185** [comment]
which container will  do    ping registry http://192.168.18.102, I want  to login this docker container to lookup

**Comment by 4680185** [comment]
我需要怎么做才能让我的container能够解析"registrybackup.ctyun.cn"

**Comment by ywk253100** [comment]
Add "extra_hosts" label to ui container in docker-compose.yml, see docker compose usage for detail information. Or replace the hostname with IP.
