### ISSUE TITLE
The endtime should be empty if a replication job in pending status.

### ISSUE THREAD

**Issue by yixingjia** [vmware/harbor#2869]
Now if a job in pending status it shows endtime same as start time.

**Comment by steven-zou** [comment]
@reasonerjt @ywk253100 

Here is the data returned by API, as no 'end_time', currently, treat 'update_time' as 'end_time'. So, at the first steps, these two timestamps might be same. To resolve this problem, I think the API should be enhanced to support 'end_time'. (Discussed with @ywk253100 , letting UI use status and update timestamp together to adjust whether the end_time is ready is not suitable because that might cause different behaviors between uI and api calling).

{
    "id": 20,
    "status": "finished",
    "repository": "library/photon",
    "policy_id": 2,
    "operation": "transfer",
    "tags": null,
    "creation_time": "2017-07-27T02:10:19Z",
    "update_time": "2017-07-27T02:10:44Z"
  },

**Comment by steven-zou** [comment]
Discussed with @ywk253100 , to keep consistent between UI and API, let's directly use 'Update time' to instead of 'End Time'. This is a simple solution.

**Comment by steven-zou** [comment]
Changed column label to 'Update time', code merged in PR #2885
