### ISSUE TITLE
[UI] The scan button should shows at conspicuous place.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#2893]
![image](https://user-images.githubusercontent.com/2841473/28662969-de0f8584-7270-11e7-9b9b-3d27731aa83c.png)

**Comment by steven-zou** [comment]
Any suggestions? @lweitzman @tonycgil

**Comment by lweitzman** [comment]
we do show the "Scan Now" action in the vulnerability column when a scan hasn't taken place yet. 
i think that having it in the context menu is a reasonable solution. @karthik-narayan ?
another alternative is to be able to select a row (requires a checkbox at the beginning of each row) and a "Scan" action appears above the table

**Comment by steven-zou** [comment]
@lweitzman 

   Currently only show the scanning status in the 'Vulnerability' column, the only action triggering entrance is the 'scan' menu item which is available when the status is not 'pending' and 'scanning'.

   About the checkbox solution, as stack view adopted in our portal, it seems not clear to use radio box at the beginning of each column.

**Comment by lweitzman** [comment]
@steven-zou the original mockups showed a "SCAN NOW" action in the vulnerability column if a scan had not taken place yet. 
![screen shot 2017-07-31 at 9 18 24 am](https://user-images.githubusercontent.com/626032/28779480-4c28d1e8-75d1-11e7-816d-e8a45c16dc7d.png)

i agree that using the checkbox is not a good solution.

**Comment by steven-zou** [comment]
@lweitzman 

  Yeah, I know the original mockup. But there is obvious problem: The 'scanning' can happen at any status except "running" and "queued", the original mockup just supports scanning the unscanned image. 

  We need to rethink and redesign the UX of this part.

**Comment by lweitzman** [comment]
@steven-zou so you don't think people will understand the context menu access via the 3 dots at the beginning of the row? thats the standard way to take an action on an individual item.  i want to avoid the clarity pattern of selecting a row (i.e., the check box at the beginning of the row) only then could we have a visible action above the data grid. this is further complicated because of the embedded nature of the inner datagrid

**Comment by steven-zou** [comment]
@lweitzman 
  Some comments from brad：
“The point I am making is that I had to make a series of assumptions to interpret how the system would behave based on the threshold I set and the colors I see in the stacked bar. I like the stacked bar view since it conveys a great deal of information so I don’t want it replaced but maybe a new column can be added with the resulting severity based on your chart below (provided that’s the way the system actually works). I’m not sure what the best approach is here and will defer to UX and harbor engineers.”

We need also consider this suggestion, right?

**Comment by steven-zou** [comment]
My previous solution:
--------
Brad,
 
  Just a confirmation, do you mean the severity level of one tag is determined by the vulnerability severities with the following mapping relations?
 
  ------------------------------------------------------------------------------------
  Tag Severity       |          Vulnerability Severities
  ------------------------------------------------------------------------------------
High             |   at least one high level vulnerability
  ------------------------------------------------------------------------------------
Medium           |   no high level ones, at least one medium vulnerability
  ------------------------------------------------------------------------------------
Low              |   no high and medium level ones, at least one low vulnerability
  ------------------------------------------------------------------------------------
None             |   no any vulnerabilities
  ------------------------------------------------------------------------------------
 
  For the UI view (in the tag list of stack view) part, only show the final tag severity with corresponding texts like ‘High’, ’Medium’, ’Low’ and ‘None’?
--------

**Comment by lweitzman** [comment]
@steven-zou i'm not quite sure i understand what @bradmeiseles is asking for here. doesn't an image have a variety of vulnerabilities in the different packages that are included? what would be in the new column that brad is suggesting? to see the breakdown you drill into the image details to get that information.

**Comment by steven-zou** [comment]
<img width="425" alt="screen shot 2017-08-03 at 1 05 01 pm" src="https://user-images.githubusercontent.com/5753287/28951362-292057b4-78fd-11e7-9eb8-33abd9a42dcb.png">
