### ISSUE TITLE
The repo list in the "Repository" tab of project does not work well

### ISSUE THREAD

**Issue by mshipkovenski** [vmware/harbor#2996]
This issue is a response to
https://github.com/vmware/admiral/issues/149

> No repo data are loaded;
>No 'systeminfo' API is called;
>If you click the refresh button, then the repo list is shown.
>It is the same sharable component with the repo list in 'Project repositories' which does work well.
>Please check if there are missing some properties or services binding, for example " @input() projectId"

The reason behind this behavior is that when the page is loaded there's a ui call to the backend to fetch the projectId. Meanwhile the harbor component is initialized with null value. After the delay, the projectId is injected and it should be handled by ngOnChange, rather than ngOnInit.

**Comment by steven-zou** [comment]
@mshipkovenski 
 
  I know "ngChanges" can resolve the problem, but it seems not a good point to place the initializing code because it's a multiple called method. To put code in it, we need to add the code in 'if' block, right? ngInit is only called once and seems more suitable to put initializing code here.
   
  One more question, why the 'projectId' is not a 'instant ready property'?  Now that an API must be called to get the project Id, why not creating a resolver to prepare the id before rendering the view?

**Comment by steven-zou** [comment]
@mshipkovenski  Whether having all components rendered immediately or not really depends on cases. Obviously, rendering them all will make the initial loading take longer time, that may not be good experiences. In addition, most of time, user may not touch all of the components. The time spending on the untouched components will be wasted, right?

I still think putting the initial action in the 'ngChanges' which is a multiple called hook method is not suitable. Initial action should be in the initial hook like 'ngInit' which will be only called once.

About my question, I did not mean 'make all the data instantly ready'. As you know, in the project detail component, there are many sub components which depends on the key data '**projectId**'. What I mean using **Angular resolver** to prepare the '**projectId**' ready before starting to rendering/loading other data. That's the way we adopted in Harbor standalone portal. We have a project detail component with multiple sub components like Admiral in the standalone portal too.

What do you think?

**Comment by shadjiiski** [comment]
@steven-zou (copied from https://github.com/vmware/admiral/issues/149)

> Whether having all components rendered immediately or not really depends on cases. Obviously, rendering them all will make the initial loading take longer time, that may not be good experiences. In addition, most of time, user may not touch all of the components. The time spending on the untouched components will be wasted, right?

The difference between rendering all components at once or having them load on demand should be negligible (this is HTML after all). What takes the most time is rendering the contents of a component because it depends on loading data from the backend. However, provided that all requests to the backend are asynchronous, that they are not constantly resent and that they are a reasonably low number of requests, loading the content for all components simultaneously should not take more time than loading each component sequentially on demand. Also, a user would prefer having the contents of a datagrid preloaded and readily displayed when he access the tab. Loading tab content only on opening the tab will surely look not as convenient, especially when that tab has a reload button for its content.

The idea that @mshipkovenski was talking about was that it is better to have the data grid in the repositories tab rendered but displaying a loading indicator than having the tab display a loading indicator that is to be replaced with the populated data grid.

> I still think putting the initial action in the 'ngChanges' which is a multiple called hook method is not suitable. Initial action should be in the initial hook like 'ngInit' which will be only called once.

Well, you seem to be right, you need to call your initialization code just once. Actually, I have checked the [repository stack component sources](https://github.com/vmware/harbor/blob/a1a36a4cc44792e1e2f0f35296bcb050992bb16d/src/ui_ng/lib/src/repository-stackview/repository-stackview.component.ts#L130) and it looks like the only thing that you are doing related to the `projectId` is a check whether it exists or not. It looks like your call that loads the system info makes no use of the `projectId` whatsoever so it makes no sense breaking the initialization when that `projectId` is not set. I think you should keep your initialization code in the `ngOnInit` method but also implement the `ngOnChanges` as well where you can just the `projectId` change. Actually, the only thing you need to do there is to call `refresh()` if the `projectId` is currently defined (and has changed from the last invocation). Since this is a library component (or at least it is under the lib dir) I would assume that there would be a user that will think that changing the bound `projectId` property will be just enough to programatically make the component reload and display data for another project. Implementing the `ngOnChanges` will save you a lot of trouble in those cases.

> What I mean using Angular resolver to prepare the 'projectId' ready before starting to rendering/loading other data.

I am not a UI expert, so I am not sure what value will/won't have such an approach. However, in Admiral we design our views to display as much useful information as we can currently. Also, if anything updates, we try to update the views accordingly. This would mean that we would prefer to display data that is currently available and replace a few loading indicatorts and placeholders with real data when it is available.

**Comment by steven-zou** [comment]
@shadjiiski 
  The initial data of stack view contains two parts, one is the repo list data and another one is some auxiliary data returned by the systeminfo call. The initial code is put in the only-once-called method 'ngOnInit'. As the 'projectId' is the key precondition for the main data preparation process, if it is unset, the followup methods call will make no sense including the systeminfo. So fast return should be meaningful.

>The difference between rendering all components at once or having them load on demand should be negligible (this is HTML after all). What takes the most time is rendering the contents of a component because it depends on loading data from the backend. However, provided that all requests to the backend are asynchronous, that they are not constantly resent and that they are a reasonably low number of requests, loading the content for all components simultaneously should not take more time than loading each component sequentially on demand. Also, a user would prefer having the contents of a datagrid preloaded and readily displayed when he access the tab. Loading tab content only on opening the tab will surely look not as convenient, especially when that tab has a reload button for its content.

About this part, I think there are some misunderstanding about the data rendering. What I mean is the whole rendering process including the data retrieving.

To save time, I'd like to **close** this discussion. We can add code in the ngChanges with if block, but I still think it's not the right place to put these initialization code. I'm not an UI expert too.

For the Angular resolver I mentioned before, you can check it [here](https://angular.io/guide/router#resolve-pre-fetching-component-data).

**Comment by steven-zou** [comment]
@shadjiiski 

We use the Clarity data grid server-driven data retrieving approach. The first call is controlled by Clarity. Refer [server-driven](https://vmware.github.io/clarity/documentation/datagrid/server-driven)

`<clr-datagrid (clrDgRefresh)="clrLoad($event)" [clrDgLoading]="loading">`

**Comment by steven-zou** [comment]
As issue is fixed in harbro-ui@0.4.46, close this issue
