### ISSUE TITLE
docker registry garbage collection Is there any plan support?

### ISSUE THREAD

**Issue by jinghuaz** [vmware/harbor#3342]
Hi guys:

  I would like to ask if there are configuration settings that can perform docker registry garbage collection periodically, just like docker trusted registry, with a scheduled task setting on the WEB UI.wait...hope...

JingHua Zhou

**Comment by reasonerjt** [comment]
Current implementation of Registry requires to run another registry process to do the GC.  It can be done when Harbor is deployed on single node.
But it will be problematic if Harbor is deployed distributed, i.e. there's no good way to trigger all platform to start a process on selected node without special support from the platform.

**Comment by Vanuan** [comment]
README states:

> Image deletion & garbage collection: Images can be deleted and their space can be recycled.

Apparently, it's no more than a UI for docker/distribution environment variable REGISTRY_STORAGE_DELETE_ENABLED + gc command on startup.

Harbor doesn't have and doesn't do any more than [docker/distribution](https://github.com/docker/distribution) does regarding garbage collection.

The current status in docker registry is the following:

1. You must delete a manifest for the space to be reclaimed. Otherwise an image blob remains reachable by API. There's no way to [garbage collect untagged manifests](https://github.com/docker/distribution/issues/1844).
2. You can't list untagged manifests. You must preserve tags for being able to delete manifests. There's a [pull request to enable listing manifests](https://github.com/docker/distribution/pull/2199) so that one can delete them.
3. To delete a manifest you have to have REGISTRY_STORAGE_DELETE_ENABLED environment varialbe to be set for the docker registry service.
4. After you delete the manifest you still must shut down registry, run the garbage collect command and start the registry. There's no way to garbage collect on the fly.

**Comment by jinghuaz** [comment]
I tried DTR, and they had a function that could set the timed cron task to execute the GC command.
Another question: why is the popular mirrored warehouse on the UI page always empty? In fact, I already have a lot of image working on it.

**Comment by Vanuan** [comment]
It looks like that [Docker Trusted Registry 2.2 Garbage Collection](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/garbage-collection/) uses the following:

1) An a new registry process is started with [read only option](https://docs.docker.com/registry/configuration/#readonly) set to true
2) Read write registry is brought down
3) A garbage collection process reclaims disk space
4) Read write registry is started
5) Read only registry is shut down.

**Comment by reasonerjt** [comment]
@jinghuaz As for the DTR case, it's based on UCP(last time I checked it was), so it can rely on UCP to start new instance of registry, this is not true for Harbor as it may be deployed on different platform.

As for the other question, please open a new issue.

**Comment by bendyna-vitalii** [comment]
Hello!
You wrote, that: Current implementation of Registry requires to run another registry process to do the GC. It can be done when Harbor is deployed on single node.
But what in case the storage is located on S3? I didn't find any information about it in the Internet
