### ISSUE TITLE
Clair download goes to different sites from the one in docs

### ISSUE THREAD

**Issue by andrewtchin** [vmware/harbor#3524]
@sgtserge commented on [Fri Oct 27 2017](https://github.com/vmware/vic-product/issues/994)

We are using VIC 1.2.1 GA on vSphere 6.0 u3a and vCenter 6.0 u3b

We are trying to set up Clair to work behind a proxy so we have to provide a list of required sites.

In Clair doc available here I can see the Database URLs are all on github

But in Clair logs I see that it tries to go on these other sites:

Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Oracle's update list","Level":"error","Location":"oracle.go:134","Time":"2017-10-26 21:56:39.132198","error":"Get **https://linux.oracle.com**/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Oracle's update list","Level":"error","Location":"oracle.go:134","Time":"2017-10-26 21:56:39.178998","error":"Get https://linux.oracle.com/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download RHEL's update list","Level":"error","Location":"rhel.go:106","Time":"2017-10-26 21:56:39.179353","error":"Get **https://www.redhat.com**/security/data/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Debian's update","Level":"error","Location":"debian.go:68","Time":"2017-10-26 21:56:39.179831","error":"Get **https://security-tracker.debian.org**/tracker/data/json: Forbidden"}

This log filled up the disk in just 1 day making VIC appliance to crash, which is not expected to happen. Maybe it is possibile to increase log rotation for this log file.

Thanks

Sergio

**Comment by reasonerjt** [comment]
This is due to issue in Clair's code, the user setup firewall in his env and returned error to Clair it cannot handle.

I'll check Clair's code and contact Clair's developer to see if it's possible better handle this scenario, but it is beyond our control.

Also it is unclear where did the user get information to draw this conclusion:
```
In Clair doc available here I can see the Database URLs are all on github
```
This is clearly incorrect.

**Comment by sgtserge** [comment]
Link to doc [here](https://github.com/vmware/vic-product/pull/933/files/71dcf3c67dfbcafb1a82a907f8d19dbc4a777734#diff-db5efe2786c724bae36c026c79ce787e)

And here is a quote:

> +## Vulnerability Scanning
 +
 +vSphere Integrated Containers uses the open source project Clair to scan images for known vulnerabilities. Cloud administrators and DevOps administrators can set threshold values that restrict vulnerable images that exceed the threshold from being run on a per-project level. Once an image is uploaded into the registry, Clair checks the various layers of the image against known vulnerability databases and reports issues to the administrators.
 +
 +**Prerequisites**
 +
 +You must provide access from your vSphere Integrated Containers instance to the following URLs so that Clair can sync its database.
 +
 +|Item|Database URL|
 +|---|---|
 +|Ubuntu  |[Ubuntu database URL](https://github.com/coreos/clair/blob/6663bcef27b0a4221831a1ff7a05477247188b09/ext/vulnsrc/ubuntu/ubuntu.go#L40)|
 +|Red Hat Enterprise Linux    |[Rhel database URL](https://github.com/coreos/clair/blob/6663bcef27b0a4221831a1ff7a05477247188b09/ext/vulnsrc/rhel/rhel.go#L38)|
 +|Oracle  |[Oracle database URL](https://github.com/coreos/clair/blob/6663bcef27b0a4221831a1ff7a05477247188b09/ext/vulnsrc/oracle/oracle.go#L39)|
 +|Debian  |[Debian database URL](https://github.com/coreos/clair/blob/6663bcef27b0a4221831a1ff7a05477247188b09/ext/vulnsrc/debian/debian.go#L37)|
 +|Alpine  |[Alpine database URL](https://github.com/coreos/clair/blob/6663bcef27b0a4221831a1ff7a05477247188b09/ext/vulnsrc/alpine/alpine.go#L37)|
 +|National Vulnerability Database|[NIST NVD database URL](https://github.com/coreos/clair/blob/release-2.0/ext/vulnmdsrc/nvd/nvd.go#L41)|

**Comment by reasonerjt** [comment]
@sgtserge 
Actually the links are reference to Clair's code which has assignment to constant to point to internet URLs.  You can click the links to find out the values of the URLs.
Sorry for the confusion, we should clarify in the document.

**Comment by reasonerjt** [comment]
Closing as the doc has been refined.
