### ISSUE TITLE
Align the harbor build number with CI job ID to avoid confusion.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#3973]
So far the build id is using "git describe --tags" to generate, but it somehow will confuse us.
Change the build id to ${Drone_Job_ID}+${Git_Commit} is more reasonable.

**Comment by jessehu** [comment]
Thanks Yan.Currently the content of https://storage.googleapis.com/harbor-builds/latest.build is something like "https://storage.googleapis.com/harbor-builds/harbor-offline-installer-v1.3.0-rc1-214-g5456c0b.tgz". The version v1.3.0-rc1 is confusing since this build is actually a post v1.3.0 GA build.

**Comment by wy65701436** [comment]
Close it as https://ci.vcna.io/vmware/harbor/2011
