### ISSUE TITLE
Log rotation seems wrong for long run.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#3990]
1,I get one log with name ui.log.1, it should be ui.log.1.gz
2,I get ui.log.8/9/10.gz, but no ui.log.2-6.gz.

**Comment by ywk253100** [comment]
The log container is restarting every a few seconds in the long run env where the issue is found.

For 1, when `logrotate` was trying to compress the `ui.log.1`, the container was stopped. This caused that `ui.log.1` was not compressed.

For 2, `logrotate` runs in two steps. Firstly, it renames `ui.log.n.gz` to `ui.log.n+1.gz`. And secondly, it creates a new `ui.log.1` and copy logs from `ui.log` to `ui.log.1`. As `ui.log.1` was not compressed correctly, the creation failed. This caused no new `ui.log.1.gz` was created. 

So the issue is caused by the env, not the log service.
