### ISSUE TITLE
Harbor Tile status shows failure after Harbor VM is rebooted manually or by vSphere HA

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4326]
Reported by https://jira.eng.vmware.com/browse/PKS-600

**Comment by steven-zou** [comment]
Reproduced the issue by power off and power on the Harbor VM. A quick look, seems the harbor hostname cannot be resolved after power on and then cause the status checker to return failure to the monit process (All the harbor container services are successfully started). Will do more investigations to locate the root cause soon.

**Comment by reasonerjt** [comment]
The bosh-dns is not started after HA or power on/off

**Comment by jessehu** [comment]
I confirm it's due to bosh-dns is started but not enabled in /etc/resolve.conf because it's enabled via a pre-start job which will not be executed after VM rebooted : https://git.eng.vmware.com/harbor/habo/blob/master/jobs/enable-bosh-dns/templates/pre-start
Will follow the fix in pks-helpers-release https://github.com/pivotal-cf/pks-helpers-release/commit/2cd97725328f7e92f1e786a93ba0253452ab37bb to fix this bug.

**Comment by jessehu** [comment]
Fixed by https://gitlab.eng.vmware.com/harbor/habo/merge_requests/25

**Comment by jessehu** [comment]
1 more patch: Enable bosh dns in pre-start because harbor pre-start requires it https://git.eng.vmware.com/harbor/habo/merge_requests/27
