### ISSUE TITLE
Sorting projects by access level does not work

### ISSUE THREAD

**Issue by LoLei** [vmware/harbor#5341]
In the projects view, I can sort projects by all other columns, but not by access level, i.e. public and private. The little arrow in the column header changes when I click it, but the projects are just sorted alphabetically (ascending, A-Z) again, every time I click it.

**Harbor version:** Version v1.5.1-8bbd84ea
**Docker version:** Docker version 1.10.3, build 20f81dd
**docker-vompose version:** docker-compose version 1.22.0-rc2, build 6817b533

I did not change much in the config files except the hostname, HTTPS and port.
The logs show nothing obvious, no errors. I can post them if nobody can reproduce it but I don't think it's necessary.

**Comment by reasonerjt** [comment]
Please check if this is bug or limitation of the datagrid in clarity.

**Comment by LoLei** [comment]
May I ask why this was closed? Has it been fixed in a recent PR? I can't seem to find a relevant one.

**Comment by zhoumeina** [comment]
Hi Lorenz,

It was fixed by pull request  https://github.com/vmware/harbor/pull/5456.

I linked it with this pull request.

Regards,
Mia


发件人: Lorenz Leitner <notifications@github.com>
答复: vmware/harbor <reply@reply.github.com>
日期: 2018年8月3日 星期五 下午10:21
收件人: vmware/harbor <harbor@noreply.github.com>
抄送: Meina Zhou <meinaz@vmware.com>, State change <state_change@noreply.github.com>
主题: Re: [vmware/harbor] Sorting projects by access level does not work (#5341)


May I ask why this was closed? Has it been fixed in a recent PR? I can't seem to find a relevant one.
