### ISSUE TITLE
Error of docker-compose.yml.daocloud

### ISSUE THREAD

**Issue by fenglvming** [vmware/harbor#598]
registry:
    image: daocloud.io/library/registry:2.3.0
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    ports:
      - 5001:5001
    command:
      /etc/registry/config.yml
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "registry"  
-------------------------------要修改为：
registry:
    image: daocloud.io/library/registry:2.4.0
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    ports:
      - 5001:5001
    command:
      ["serve","/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "registry"

**Comment by wemeya** [comment]
@fenglvming 
It has been a long time since I last update this yml. Right now, I have submitted a PR for the newest configuration to pull from docker hub or daocloud instead of build. You can view that PR to see the changes, the biggest change is that we add a script to automatic configure the platform you preferred to pull from. Just have a try! We will merge it to master soon. See below:
[https://github.com/vmware/harbor/pull/574](url)

**Comment by wemeya** [comment]
@fenglvming 
already merged into master, pls have a check.

**Comment by wemeya** [comment]
@fenglvming 
If no question, pls close the issue, or we'll close it later. You're welcome and feel free to reopen it if you have further questions .
