### ISSUE TITLE
First install of harbor failed, but immediately afterwards succeeded

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/harbor#898]
```
root@ddccd19b6bf4:/go# ovftool harbor_0.4.1_beta.ova harbor_0.4.1_beta.ovf 
Opening OVA source: harbor_0.4.1_beta.ova
The manifest validates
Opening OVF target: harbor_0.4.1_beta.ovf
Writing OVF package: harbor_0.4.1_beta.ovf
Transfer Completed                    
Completed successfully


root@ddccd19b6bf4:/go# ovftool --datastore=datastore1 --name=harbor --net:"Network 1"="VM Network" --diskMode=thin --powerOn --X:waitForIp --X:injectOvfEnv --X:enableHiddenProperties --prop:vami.domain.Harbor=mgmt.local --prop:vami.searchpath.Harbor=mgmt.local --prop:vami.DNS.Harbor=8.8.8.8 --prop:vm.vmname=Harbor harbor_0.4.1_beta.ovf 'vi://root:xxxx@192.168.254.128'
Opening OVF source: harbor_0.4.1_beta.ovf
The manifest validates
Accept SSL fingerprint (E5:87:9A:A6:E6:49:03:6D:F6:84:61:95:9F:11:36:97:A7:6F:10:E6) for host 192.168.254.128 as target type.
Fingerprint will be added to the known host file
Write 'yes' or 'no'
yes
Opening VI target: vi://root@192.168.254.128:443/
Warning:
 - The specified operating system identifier 'PhotonOS Technical Preview 2' (id: 85) is not supported on the selected host. It will be mapped to the following OS identifier: 'Other (32-bit)'.
Deploying to VI: vi://root@192.168.254.128:443/
Transfer Completed                    
Error: vim.fault.InvalidState
Error: vim.fault.InvalidState
Completed with errors


root@ddccd19b6bf4:/go# ovftool --datastore=datastore1 --name=harbor --net:"Network 1"="VM Network" --diskMode=thin --powerOn --X:waitForIp --X:injectOvfEnv --X:enableHiddenProperties --prop:vami.domain.Harbor=mgmt.local --prop:vami.searchpath.Harbor=mgmt.local --prop:vami.DNS.Harbor=8.8.8.8 --prop:vm.vmname=Harbor harbor_0.4.1_beta.ovf 'vi://root:xxxxx@192.168.254.128'
Opening OVF source: harbor_0.4.1_beta.ovf
The manifest validates
Opening VI target: vi://root@192.168.254.128:443/
Warning:
 - The specified operating system identifier 'PhotonOS Technical Preview 2' (id: 85) is not supported on the selected host. It will be mapped to the following OS identifier: 'Other (32-bit)'.
Deploying to VI: vi://root@192.168.254.128:443/
Transfer Completed                    
Powering on VM: harbor
Task Completed                        
Received IP address: 192.168.254.164
Completed successfully
```

ESX log:

[esx-localhost-2016-10-18--15.20.zip](https://github.com/vmware/harbor/files/536682/esx-localhost-2016-10-18--15.20.zip)

**Comment by reasonerjt** [comment]
First time seeing the log
I don't see any logs have information about importing the ova, however I see quite a few invalid state error in hostd.log:

_./var/run/log/hostd.log:2016-10-17T15:46:00.002Z error hostd[45DA1B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'931',WID:39525): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState_

_./var/run/log/hostd.log:2016-10-17T15:46:18.306Z warning hostd[463C2B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/573f3c77-f5dc6515-f2ad-000c2938cb96/amazing_blackwe-781aaffccd2d6a26caccb66e9bdfc664a040f7d7652d08504241983560c44871/amazing_blackwe-781aaffccd2d6a26caccb66e9bdfc664a040f7d7652d08504241983560c44871.vmx opID=58ae6955 user=root] CannotRetrieveCorefiles: VM is in an invalid state_

_./var/run/log/hostd.log:2016-10-17T15:46:18.700Z info hostd[45DE2B70] [Originator@6876 sub=Vigor.Vmsvc.vm:/vmfs/volumes/573f3c77-f5dc6515-f2ad-000c2938cb96/amazing_blackwe-781aaffccd2d6a26caccb66e9bdfc664a040f7d7652d08504241983560c44871/amazing_blackwe-781aaffccd2d6a26caccb66e9bdfc664a040f7d7652d08504241983560c44871.vmx] Could not retrieve Bootstrap state: N3Vim5Fault12InvalidState9ExceptionE(vim.fault.InvalidState)
./var/run/log/hostd.log:2016-10-17T16:19:40.002Z error hostd[463C2B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'932',WID:39715): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState_

_./var/run/log/hostd.log:2016-10-18T15:10:15.559Z info hostd[39940B70] [Originator@6876 sub=Default opID=72038037 user=root] AdapterServer caught exception: vim.fault.InvalidState
./var/run/log/hostd.log:2016-10-18T15:10:15.560Z info hostd[39940B70] [Originator@6876 sub=Solo.Vmomi opID=72038037 user=root] Throw vim.fault.InvalidState_

I'm not sure which error is the one you met when importing the ova, but seems to me this is a env issue rather than issue in the .ova file.

**Comment by reasonerjt** [comment]
We don't see any problems when importing recently built ova, will close this issue, feel free to reopen if you reproduce the issue. @mhagen-vmware
